# Generated by Django 3.1.5 on 2022-06-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sriapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=5)),
                ('bname', models.CharField(max_length=10)),
                ('slt', models.CharField(max_length=100)),
                ('prof', models.CharField(max_length=100)),
            ],
        ),
    ]
