# Generated by Django 4.0.5 on 2022-06-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sriapp', '0003_c_pref_time_to_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_pref',
            name='fr10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='fr12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='fr8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='mn10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='mn12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='mn8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='th10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='th12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='th8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='tu10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='tu12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='tu8',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='wd10',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='wd12',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='c_pref',
            name='wd8',
            field=models.IntegerField(),
        ),
    ]
