# Generated by Django 4.0.5 on 2022-06-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sriapp', '0005_alter_c_pref_fr10_alter_c_pref_fr12_alter_c_pref_fr8_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='C_pref',
        ),
    ]
