# Generated by Django 4.0.5 on 2022-06-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sriapp', '0006_delete_c_pref'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slt', models.CharField(max_length=100)),
                ('mn8', models.IntegerField(default=0)),
                ('mn10', models.IntegerField(default=0)),
                ('mn12', models.IntegerField(default=0)),
                ('tu8', models.IntegerField(default=0)),
                ('tu10', models.IntegerField(default=0)),
                ('tu12', models.IntegerField(default=0)),
                ('wd8', models.IntegerField(default=0)),
                ('wd10', models.IntegerField(default=0)),
                ('wd12', models.IntegerField(default=0)),
                ('th8', models.IntegerField(default=0)),
                ('th10', models.IntegerField(default=0)),
                ('th12', models.IntegerField(default=0)),
                ('fr8', models.IntegerField(default=0)),
                ('fr10', models.IntegerField(default=0)),
                ('fr12', models.IntegerField(default=0)),
            ],
        ),
    ]
