# Generated by Django 4.0.5 on 2022-06-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sriapp', '0007_c_pref'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=100)),
                ('cnt', models.IntegerField(default=0)),
            ],
        ),
    ]
