# Generated by Django 4.0.5 on 2022-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sriapp', '0009_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='type',
            field=models.CharField(default='core', max_length=100),
            preserve_default=False,
        ),
    ]
